ae_compta_homepage:
    path:     /hello/{name}
    defaults: { _controller: AEComptaBundle:Default:index }

ae_compta_simulation_save:
    path:     /simulation/save
    defaults: { _controller: AEComptaBundle:Simulation:saveImpotsMensuels }

ae_compta_simulation_update:
    path:     /simulation/update
    defaults: { _controller: AEComptaBundle:Simulation:updateImpotsMensuels }
