a_eplatform_homepage:
    path:     /hello
    defaults: { _controller: AEplatformBundle:Default:index }

page_d_accueil:
    path:    /
    defaults: {_controller: AEplatformBundle:Advert:homepage }

page_faq:
    path:   /faq
    defaults: {_controller: AEplatformBundle:Advert:faq}

dashboard_user:
    path:   /dashboard
    defaults: {_controller: AEplatformBundle:Dashboard:dashboard}

new_entreprise_user:
    path:   /nouvelle-entreprise
    defaults: {_controller: AEplatformBundle:Entreprise:newEntreprise}

show_entreprise_user:
    path:   /mon-entreprise
    defaults: {_controller: AEplatformBundle:Entreprise:showEntreprise}

edit_entreprise_user:
    path:     /mon-entreprise/{id}/edit
    defaults: { _controller: AEplatformBundle:Entreprise:editEntreprise }

update_entreprise_user:
    path:     /mon-entreprise/{id}/update
    defaults: { _controller: AEplatformBundle:Entreprise:update }
    methods:  [POST, PUT]

delete_entreprise_user:
    path:     /mon-enteprise/{id}/delete
    defaults: { _controller: AEplatformBundle:Entreprise:delete }
    methods:  [POST, DELETE]