factures:
    path:     /
    defaults: { _controller: "AEDashBundle:Factures:index" }

factures_show:
    path:     /{id}/show
    defaults: { _controller: "AEDashBundle:Factures:show" }

factures_new:
    path:     /new
    defaults: { _controller: "AEDashBundle:Factures:new" }

factures_create:
    path:     /create
    defaults: { _controller: "AEDashBundle:Factures:create" }
    methods:  POST

factures_edit:
    path:     /{id}/edit
    defaults: { _controller: "AEDashBundle:Factures:edit" }

factures_update:
    path:     /{id}/update
    defaults: { _controller: "AEDashBundle:Factures:update" }
    methods:  [POST, PUT]

factures_delete:
    path:     /{id}/delete
    defaults: { _controller: "AEDashBundle:Factures:delete" }
    methods:  [POST, DELETE]

factures_twig_to_pdf:
    path:     /{id}/twig-to-pdf
    defaults: { _controller: "AEDashBundle:Factures:twigToPdf" }